# These are supported funding model platforms

github: [santhoshsharuk]
open_collective: santhosh-sharuk
ko_fi: santhoshsharuk
liberapay: santhosh_sharuk
buy_me_a_coffee: https://buymeacoffee.com/santhoshsharuk
